# Generated by Django 5.0.6 on 2024-07-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm_app', '0002_rename_name_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
