# Generated by Django 5.0.6 on 2024-07-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lm_app', '0004_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='from_date',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='to_date',
            new_name='date_to',
        ),
    ]
