# Generated by Django 5.0.6 on 2024-07-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm_app', '0005_rename_from_date_students_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='total_days',
            field=models.IntegerField(default=1),
        ),
    ]
