# Generated by Django 5.0.6 on 2024-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm_app', '0006_students_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='total_days',
            field=models.IntegerField(),
        ),
    ]
