# Generated by Django 5.0.6 on 2024-07-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm_app', '0007_alter_students_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
