# Generated by Django 5.0.6 on 2024-07-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm_app', '0008_students_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
